/**
 * The learning-material catalog — the single source of truth for both the
 * landing-page listing and the Starlight sidebar.
 *
 * Adding a material: create `src/content/docs/<slug>/` with an `index.md`,
 * add a `sections` entry per subdirectory, then append the material here.
 * Nothing else needs to change — `astro.config.mjs` and `src/pages`-free
 * routing pick it up automatically.
 */

export interface MaterialSection {
  /** Label shown as the sidebar group heading. */
  label: string;
  /** Directory under `src/content/docs/<slug>/`, autogenerated into the sidebar. */
  directory: string;
}

export interface Material {
  /** URL segment and content directory name, e.g. `java-spring-boot`. */
  slug: string;
  /** Display title, used on the card and as the sidebar group label. */
  title: string;
  /** One-line summary for the catalog card. */
  description: string;
  /** Longer pitch shown on the material's own landing section. */
  tagline: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  /** Rough size, e.g. "26 steps". Shown on the card. */
  size: string;
  tags: string[];
  status: 'available' | 'draft' | 'planned';
  /** Page a reader should land on from the catalog card. */
  entry: string;
  /** Extra top-level sidebar links rendered above the section groups. */
  links: { label: string; slug: string }[];
  sections: MaterialSection[];
}

export const materials: Material[] = [
  {
    slug: 'java-spring-boot',
    title: 'Java with Spring Boot',
    description:
      'Go from "I know Java, new to Spring" to a production-grade backend and fullstack app, built around one real domain: an event ticketing marketplace.',
    tagline:
      'Twenty-six steps, one real domain. Concurrency, consistency, and distributed-systems reasoning you cannot fake with a todo app.',
    level: 'Intermediate',
    size: '26 steps',
    tags: ['Java 21', 'Spring Boot 3.5', 'PostgreSQL', 'React', 'AI-assisted'],
    status: 'available',
    entry: 'java-spring-boot/getting-started',
    links: [
      { label: 'Overview', slug: 'java-spring-boot' },
      { label: 'Getting Started', slug: 'java-spring-boot/getting-started' },
    ],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
];

export const publishedMaterials = materials.filter((m) => m.status !== 'planned');

/** Find the material that owns a given page pathname, e.g. `/java-spring-boot/setup/`. */
export function materialForPathname(pathname: string, base = '/'): Material | undefined {
  const withoutBase = pathname.slice(base.replace(/\/$/, '').length);
  const slug = withoutBase.split('/').filter(Boolean)[0];
  return materials.find((m) => m.slug === slug);
}
