/**
 * The learning-material catalog — the single source of truth for both the
 * landing-page listing and the Starlight sidebar.
 *
 * Adding a material: create `src/content/docs/<slug>/` with an `index.md`,
 * add a `sections` entry per subdirectory, then append the material here.
 * Nothing else needs to change — `astro.config.mjs` and `src/pages`-free
 * routing pick it up automatically.
 */

export interface MaterialSection {
  /** Label shown as the sidebar group heading. */
  label: string;
  /** Directory under `src/content/docs/<slug>/`, autogenerated into the sidebar. */
  directory: string;
}

export interface Material {
  /** URL segment and content directory name, e.g. `laravel-booking-saas`. */
  slug: string;
  /** Display title, used on the card and as the sidebar group label. */
  title: string;
  /** One-line summary for the catalog card. */
  description: string;
  /** Longer pitch shown on the material's own landing section. */
  tagline: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  /** Rough size, e.g. "26 steps". Shown on the card. */
  size: string;
  tags: string[];
  status: 'available' | 'draft' | 'planned';
  /** Page a reader should land on from the catalog card. */
  entry: string;
  /** Extra top-level sidebar links rendered above the section groups. */
  links: { label: string; slug: string }[];
  sections: MaterialSection[];
}

export const materials: Material[] = [
  {
    slug: 'spring-boot-ticketing',
    title: 'Spring Boot — Event Ticketing Marketplace',
    description:
      'Go from "I know Java, new to Spring" to a production-grade backend and fullstack app, built around one real domain: an event ticketing marketplace.',
    tagline:
      'Twenty-six steps, one real domain. Concurrency, consistency, and distributed-systems reasoning you cannot fake with a todo app.',
    level: 'Intermediate',
    size: '26 steps',
    tags: ['Java 21', 'Spring Boot 3.5', 'PostgreSQL', 'React', 'AI-assisted'],
    status: 'available',
    entry: 'spring-boot-ticketing',
    links: [{ label: 'Getting Started', slug: 'spring-boot-ticketing' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
  {
    slug: 'laravel-booking-saas',
    title: 'Laravel — Multi-Tenant Booking SaaS',
    description:
      'Go from "I know PHP, new to Laravel" to a production-grade multi-tenant SaaS, built around one real domain: the appointment-booking platform a barbershop, a dental clinic and a yoga studio all run on.',
    tagline:
      'Twenty-four steps, one real domain. Tenant isolation, time correctness, and money you cannot fake with a CRUD app.',
    level: 'Intermediate',
    size: '24 steps',
    tags: ['PHP 8.5', 'Laravel 13', 'PostgreSQL', 'Livewire', 'Inertia + React'],
    status: 'available',
    entry: 'laravel-booking-saas',
    links: [{ label: 'Getting Started', slug: 'laravel-booking-saas' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
  {
    slug: 'adonisjs-delivery-dispatch',
    title: 'AdonisJS — Last-Mile Delivery Dispatch',
    description:
      'Go from "I know TypeScript, new to AdonisJS" to a production-grade delivery platform, built around one real domain: the last-mile dispatch system a food stall, a pharmacy and a hardware store all run their deliveries on.',
    tagline:
      'Twenty-four steps, one real domain. Dispatch under concurrency, state machines, real time and money you cannot fake with a CRUD app.',
    level: 'Intermediate',
    size: '24 steps',
    tags: ['TypeScript 5.9', 'AdonisJS 7', 'PostgreSQL + PostGIS', 'Edge', 'Inertia + React'],
    status: 'available',
    entry: 'adonisjs-delivery-dispatch',
    links: [{ label: 'Getting Started', slug: 'adonisjs-delivery-dispatch' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
  {
    slug: 'laravel-integration-hub',
    title: 'Laravel — Business Operations Integration Hub',
    description:
      'Go from "I can build a Laravel app" to the integration work businesses pay a retainer for: webhooks that arrive twice, supplier files that arrive half-written, and money that has to reconcile.',
    tagline:
      'Twenty-two steps, one real domain. Idempotency, ordering, partial failure and reconciliation — the work that keeps paying after launch.',
    level: 'Advanced',
    size: '22 steps',
    tags: ['PHP 8.5', 'Laravel 13', 'PostgreSQL', 'Redis + Horizon', 'Webhooks + SFTP'],
    status: 'available',
    entry: 'laravel-integration-hub',
    links: [{ label: 'Getting Started', slug: 'laravel-integration-hub' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
  {
    slug: 'fastapi-support-assistant',
    title: 'FastAPI — Grounded Support Assistant',
    description:
      'Go from "I know Python, new to FastAPI" to an AI feature you can prove works — grounded answers, real citations, refusal when the documents do not say, and an evaluation report to show for it.',
    tagline:
      'Eighteen steps, one real domain. Retrieval, refusal and evaluation — the half of an AI product that separates a demo from something a clinic will use.',
    level: 'Intermediate',
    size: '18 steps',
    tags: ['Python 3.13', 'FastAPI', 'PostgreSQL + pgvector', 'Claude API', 'Evaluation'],
    status: 'available',
    entry: 'fastapi-support-assistant',
    links: [{ label: 'Getting Started', slug: 'fastapi-support-assistant' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
];

export const publishedMaterials = materials.filter((m) => m.status !== 'planned');

/** Find the material that owns a given page pathname, e.g. `/laravel-booking-saas/setup/`. */
export function materialForPathname(pathname: string, base = '/'): Material | undefined {
  const withoutBase = pathname.slice(base.replace(/\/$/, '').length);
  const slug = withoutBase.split('/').filter(Boolean)[0];
  return materials.find((m) => m.slug === slug);
}
